export const mostSearches = [
  "Flipkart Axis Bank Super Elite Credit card",
  "Primebook Laptops",
  "Bounce Infinity E1",
  "Buy Laptop on EMI",
  "Infinix Zero Book Ultra",
  "OPPO Reno8 5G",
  "OPPO Reno8 Pro 5G",
  "Fresh Flower Bouquet",
  "Holi Hampers",
  "Holi Gifts",
  "Bouquetr",
  "Oneplus Monitors",
  "Sell Old Mobile Phones",
  "Premium Laptops",
  "Electronics Store",
  "Phone cover",
  "Infinix IN",
  "Book Y1 Plus",
  "Okaya Electric Vehiclesbgauss electric scooter",
  "OPPO Reno7 Pro 5G",
  "iPhone 13",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 13 Mini",
  "Google Pixel 6a covers",
  "Flipkart Quick",
  "Ampere Magnus",
  "Flipkart Help Centre",
  "Online Boat Store",
  "Covers from Rs 99",
  "Flipkart Track Orders",
  "Flipkart Manage Orders",
  "Flipkart Return Orders",
  "Flipkart Gift Cards Store",
  "Flipkart Axis Bank Credit Card",
  "Flipkart Pay Later",
];

export const mobile = [
  "iPhone 12 64GB",
  "iPhone 12 Pro 512GB",
  "iPhone 12 128GB",
  "Vivo Y91i",
  "Vivo Y11",
  "Vivo Y15",
  "Vivo Y50",
  "Vivo Y12",
  "Reno2 F",
  "Oppo A12",
  "Oppo F15",
  "Oppo A31",
  "Samsung A71",
  "Samsung A51",
  "Samsung A31",
  "Realme X2",
  "iPhone 11",
  "iPhone 11 Pro",
  "Mobile Cover",
  "Mobile Offers",
  "iphone x4G Mobile",
  "Nokia Mobile",
  "Samsung Mobile",
  "iphone",
  "Oppo Mobile",
  "Vivo Mobile",
];

export const camera = [
  "GoPro Action Camera",
  "Nikon Camera",
  "Canon Camera",
  "Sony Camera",
  "Canon DSLR",
  "Nikon DSLR",
];

export const laptop = [
  "MacBook Pro M2",
  " Premium Laptop",
  "acer Ryzen 3 Dual Core 3250U - (8 GB/256 GB SSD/Windows 11 Home) Z2-493 Thin and Light Laptop",
  " ASUS Vivobook S14 OLED (2022)",
  "ASUS Zenbook 14 OLED (2022)",
  "Realme Book Prime Core i5 11th Gen",
  "Microsoft Surface Go Pentium 128GB",
  "Branded Laptops",
  "Apple Laptops",
  "Acer Laptops",
  "Lenovo Laptops",
  "Dell Laptops",
  "Asus Laptops",
  "HP Laptops",
  "Gaming Laptops",
  "2 in 1 Laptops",
  "Laptops",
  "Dell latest laptops 2022HP latest laptops 2022",
  "Infinix INBook Y1 Plus",
  "Microsoft Laptops",
  "12th Gen Intel Core Laptops",
];

export const tvs = [
  "Nokia TV",
  "Panasonic TV",
  "Thomson TV",
  "Vu TV",
  "Realme TV",
  "Motorola TV",
  " OnePlus TVs",
  " LG TV",
  " TV",
  " Sony TV",
  "Samsung TV",
  " Android Television",
  "Iffalcon Tv",
  "Mi TV",
];
